-- Crie essa tabela no seu projeto Supabase SQL Editor

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  text text not null,
  emoji varchar(4) not null default '💬',
  x integer not null,
  y integer not null,
  likes integer not null default 0,
  dislikes integer not null default 0,
  created_at timestamp with time zone not null default now()
);

alter table public.messages enable row level security;

create policy "Public select from messages" on public.messages
  for select using (true);

create policy "Public insert into messages" on public.messages
  for insert with check (true);

create policy "Public update messages" on public.messages
  for update using (true) with check (true);

create policy "Public delete messages" on public.messages
  for delete using (true);
