-- Crie essa tabela no seu projeto Supabase SQL Editor

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  text text not null,
  emoji varchar(4) not null default '💬',
  author_name text,
  author_ip text not null,
  latitude double precision,
  longitude double precision,
  x integer not null,
  y integer not null,
  likes integer not null default 0,
  dislikes integer not null default 0,
  created_at timestamp with time zone not null default now()
);

alter table public.messages add column if not exists author_name text;
alter table public.messages add column if not exists author_ip text;
alter table public.messages add column if not exists latitude double precision;
alter table public.messages add column if not exists longitude double precision;
update public.messages
set author_ip = 'legacy'
where author_ip is null;
alter table public.messages alter column author_ip set not null;

create or replace function public.request_ip()
returns text
language sql
stable
as $$
  select nullif(
    btrim(
      coalesce(
        split_part((current_setting('request.headers', true)::json ->> 'x-forwarded-for'), ',', 1),
        current_setting('request.headers', true)::json ->> 'x-real-ip',
        current_setting('request.headers', true)::json ->> 'cf-connecting-ip',
        current_setting('request.headers', true)::json ->> 'fly-client-ip'
      )
    ),
    ''
  );
$$;

grant execute on function public.request_ip() to anon, authenticated;

create or replace function public.lock_message_author_ip()
returns trigger
language plpgsql
as $$
begin
  if new.author_ip is distinct from old.author_ip then
    raise exception 'message author identity cannot be changed';
  end if;

  if new.author_name is distinct from old.author_name then
    raise exception 'message author identity cannot be changed';
  end if;

  return new;
end;
$$;

drop trigger if exists messages_lock_author_ip on public.messages;
create trigger messages_lock_author_ip
before update on public.messages
for each row
execute function public.lock_message_author_ip();

alter table public.messages enable row level security;

drop policy if exists "Public select from messages" on public.messages;
create policy "Public select from messages" on public.messages
  for select using (true);

drop policy if exists "Public insert into messages" on public.messages;
create policy "Public insert into messages" on public.messages
  for insert with check (author_ip = public.request_ip());

drop policy if exists "Public update messages" on public.messages;
create policy "Public update messages" on public.messages
  for update using (true) with check (true);

drop policy if exists "Public delete messages" on public.messages;
create policy "Public delete messages" on public.messages
  for delete using (author_ip = public.request_ip());

notify pgrst, 'reload schema';
