-- Inicializacao local para o PostgreSQL em Docker.
-- Este script cria somente o schema necessario para a API local do projeto y.

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  text text not null,
  emoji varchar(4) not null default '💬',
  author_name text,
  author_ip text not null,
  latitude double precision,
  longitude double precision,
  x integer not null,
  y integer not null,
  likes integer not null default 0,
  dislikes integer not null default 0,
  created_at timestamp with time zone not null default now()
);

alter table public.messages add column if not exists author_name text;
alter table public.messages add column if not exists author_ip text;
alter table public.messages add column if not exists latitude double precision;
alter table public.messages add column if not exists longitude double precision;

update public.messages
set author_ip = 'legacy'
where author_ip is null;

alter table public.messages alter column author_ip set not null;
